name: Build and Deploy

on:
  push:
    branches:
      - main # Modifier si votre branche principale s'appelle autrement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Application
      run: |
        # Commandes pour construire l'application web statique (par exemple, utiliser npm, gulp, webpack, etc.)
        # Remplacez cette section par les commandes spécifiques à votre projet.

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist # Modifier si votre dossier de sortie est différent
